### PR TITLE
Feat pip continue

### PR DESCRIPTION
**Pull request by duncdrum**
@whalekeykeeper please rebase this to clean up the commit history, and add a final commit documenting the release procedure. 

If you prefer to use a tool to bump the version number thats fine, although i think we can also do that manually. In either case the steps necessary need to be documented in its own release section in the readme. 

Note: we should not use `skip_existing: true` for `PyPI` releases, its ok for `TestPyPI`. 

see #52 
see #32

### CODE REVIEW

**Comment by whalekeykeeper** [comment]
Hi @duncdrum 
Met and fixed two problems:
1. CI says there's error in yaml file but I can't find any, then read on stackoverflow that there must be a line-break before comments. After adding line-breaks, this problem is solved.
2. CI says that no event is triggered. Google and saw this: ["You must store this file in the .github directory of your repository. "](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file). After moving the `dependabot.yml` to `.github`, problem solved.

Locally, before push, I have the following:
```
(base) ➜  scripts git:(feat-pip-continue) black .
All done! ✨ 🍰 ✨
6 files left unchanged.
(base) ➜  scripts git:(feat-pip-continue) black --check . 
All done! ✨ 🍰 ✨
6 files would be left unchanged.
(base) ➜  scripts git:(feat-pip-continue) isort --profile black .         
(base) ➜  scripts git:(feat-pip-continue) isort --profile black --check . 
```
And failed the CI again.

I guess you received many CI-failure emails...
Yeah...

**Comment by duncdrum** [comment]
@whalekeykeeper good catch with the `dependabot.yml` 👍 

as for the version number `1.0.0-alpha` comes before `1.0.0` but TestPypi does accept that upload. 

back to you 🎾

**Comment by whalekeykeeper** [comment]
> @whalekeykeeper good catch with the `dependabot.yml` 👍
> 
> as for the version number `1.0.0-alpha` is more accurate, but comes before `1.0.0` luckily TestPypi does accept that upload.
> 
> back to you 🎾

wow I only read your reply now...
Uh I figured the problem of `isort` out. I should run it in the whole repository. It changes some python3.8 files which I won't see any changes from GitHub Desktop.

I want to change both the name and version of the tool. Not sure when should I do it. Haven't changed the name of the tool, but I already changed the version number into `"1.0.0-alpha"`, do you mean that it should be used before `"1.0.0"` and we used `"1.0.0"` first?

Happy to see the CI workflow is passed now.

**Comment by whalekeykeeper** [comment]
Since all the changes passed the CI, may I merge this PR?

**Comment by whalekeykeeper** [comment]
Met a failure again.
The error message is:
```
0s
Run python -m src.scripts.command_line_tool --version
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.[1](https://github.com/readchina/WikidataLookup/runs/6185514841?check_suite_focus=true#step:8:1)2/x64/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/runpy.py", line 8[7](https://github.com/readchina/WikidataLookup/runs/6185514841?check_suite_focus=true#step:8:7), in _run_code
    exec(code, run_globals)
  File "/home/runner/work/WikidataLookup/WikidataLookup/src/scripts/command_line_tool.py", line 6, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'
Error: Process completed with exit code 1.
```
And locally I have:
```
(base) ➜  WikidataLookup git:(feat-pip-continue) ✗ python3.8 -m src.scripts.command_line_tool --version
version 1.0.0

```

**Comment by whalekeykeeper** [comment]
Should I merge now?

**Pull request merged**
