### PR TITLE
Feat sparql continue

### PR DESCRIPTION
**Pull request by duncdrum**

### CODE REVIEW

**Comment by whalekeykeeper** [comment]
One question:
I tried to use `git rebase` to drop the last two commits (see above), the rebase is successful, but I didn't see any changes.
Here are commands:
```
(base) ➜  WikidataLookup git:(feat-sparql-continue) git rebase -i HEAD~4
Successfully rebased and updated refs/heads/feat-sparql-continue.
(base) ➜  WikidataLookup git:(feat-sparql-continue) git pull            
Updating 774d034..9d39555
Fast-forward
(base) ➜  WikidataLookup git:(feat-sparql-continue) git pull
Already up to date.
```
What I edited in VI is to mark the last two commits with `d`.

**Comment by duncdrum** [comment]
after the reabse you ll need to `git push --force` otherwise the commit still exist on the server, and after you pull them to your machine they are back.

**Comment by whalekeykeeper** [comment]
@duncdrum I can't set you as reviewer. Should I merge this PR? Or should I do one rebase to clean the commit history a bit?

**Comment by duncdrum** [comment]
@whalekeykeeper the changes look good, we don't need the rebase. However, the newly added test aren't currently executed on CI. Its still only running the same 11 person tests as the main branch.  Can you modify the CI so it runs all tests please. If they pass on CI this can be merged.

**Pull request merged**
